// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Messages/basics.proto

#ifndef PROTOBUF_Messages_2fbasics_2eproto__INCLUDED
#define PROTOBUF_Messages_2fbasics_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace BuiltIn {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_Messages_2fbasics_2eproto();
void protobuf_AssignDesc_Messages_2fbasics_2eproto();
void protobuf_ShutdownFile_Messages_2fbasics_2eproto();

class SetTimeScale;
class SystemRequest;
class SystemResponse;
class ChangeLogLevel;
class EmptyMessage;

enum SystemRequest_RequestType {
  SystemRequest_RequestType_SHUT_DOWN = 0,
  SystemRequest_RequestType_SERIALIZED_STATE = 1
};
bool SystemRequest_RequestType_IsValid(int value);
const SystemRequest_RequestType SystemRequest_RequestType_RequestType_MIN = SystemRequest_RequestType_SHUT_DOWN;
const SystemRequest_RequestType SystemRequest_RequestType_RequestType_MAX = SystemRequest_RequestType_SERIALIZED_STATE;
const int SystemRequest_RequestType_RequestType_ARRAYSIZE = SystemRequest_RequestType_RequestType_MAX + 1;

const ::google::protobuf::EnumDescriptor* SystemRequest_RequestType_descriptor();
inline const ::std::string& SystemRequest_RequestType_Name(SystemRequest_RequestType value) {
  return ::google::protobuf::internal::NameOfEnum(
    SystemRequest_RequestType_descriptor(), value);
}
inline bool SystemRequest_RequestType_Parse(
    const ::std::string& name, SystemRequest_RequestType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<SystemRequest_RequestType>(
    SystemRequest_RequestType_descriptor(), name, value);
}
enum SystemResponse_ResponseType {
  SystemResponse_ResponseType_SHUT_DOWN_RESPONSE = 0,
  SystemResponse_ResponseType_SERIALIZED_STATE_RESPONSE = 1,
  SystemResponse_ResponseType_LOG_LEVEL_CHANGED = 2,
  SystemResponse_ResponseType_INVALID_REQUEST = 100
};
bool SystemResponse_ResponseType_IsValid(int value);
const SystemResponse_ResponseType SystemResponse_ResponseType_ResponseType_MIN = SystemResponse_ResponseType_SHUT_DOWN_RESPONSE;
const SystemResponse_ResponseType SystemResponse_ResponseType_ResponseType_MAX = SystemResponse_ResponseType_INVALID_REQUEST;
const int SystemResponse_ResponseType_ResponseType_ARRAYSIZE = SystemResponse_ResponseType_ResponseType_MAX + 1;

const ::google::protobuf::EnumDescriptor* SystemResponse_ResponseType_descriptor();
inline const ::std::string& SystemResponse_ResponseType_Name(SystemResponse_ResponseType value) {
  return ::google::protobuf::internal::NameOfEnum(
    SystemResponse_ResponseType_descriptor(), value);
}
inline bool SystemResponse_ResponseType_Parse(
    const ::std::string& name, SystemResponse_ResponseType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<SystemResponse_ResponseType>(
    SystemResponse_ResponseType_descriptor(), name, value);
}
enum SystemResponse_ShutdownStatus {
  SystemResponse_ShutdownStatus_CLEAN_SHUTDOWN = 0,
  SystemResponse_ShutdownStatus_UNCLEAN_SHUTDOWN = 1
};
bool SystemResponse_ShutdownStatus_IsValid(int value);
const SystemResponse_ShutdownStatus SystemResponse_ShutdownStatus_ShutdownStatus_MIN = SystemResponse_ShutdownStatus_CLEAN_SHUTDOWN;
const SystemResponse_ShutdownStatus SystemResponse_ShutdownStatus_ShutdownStatus_MAX = SystemResponse_ShutdownStatus_UNCLEAN_SHUTDOWN;
const int SystemResponse_ShutdownStatus_ShutdownStatus_ARRAYSIZE = SystemResponse_ShutdownStatus_ShutdownStatus_MAX + 1;

const ::google::protobuf::EnumDescriptor* SystemResponse_ShutdownStatus_descriptor();
inline const ::std::string& SystemResponse_ShutdownStatus_Name(SystemResponse_ShutdownStatus value) {
  return ::google::protobuf::internal::NameOfEnum(
    SystemResponse_ShutdownStatus_descriptor(), value);
}
inline bool SystemResponse_ShutdownStatus_Parse(
    const ::std::string& name, SystemResponse_ShutdownStatus* value) {
  return ::google::protobuf::internal::ParseNamedEnum<SystemResponse_ShutdownStatus>(
    SystemResponse_ShutdownStatus_descriptor(), name, value);
}
// ===================================================================

class SetTimeScale : public ::google::protobuf::Message {
 public:
  SetTimeScale();
  virtual ~SetTimeScale();

  SetTimeScale(const SetTimeScale& from);

  inline SetTimeScale& operator=(const SetTimeScale& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SetTimeScale& default_instance();

  void Swap(SetTimeScale* other);

  // implements Message ----------------------------------------------

  SetTimeScale* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SetTimeScale& from);
  void MergeFrom(const SetTimeScale& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required float timeScale = 1;
  inline bool has_timescale() const;
  inline void clear_timescale();
  static const int kTimeScaleFieldNumber = 1;
  inline float timescale() const;
  inline void set_timescale(float value);

  // @@protoc_insertion_point(class_scope:BuiltIn.SetTimeScale)
 private:
  inline void set_has_timescale();
  inline void clear_has_timescale();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  float timescale_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_Messages_2fbasics_2eproto();
  friend void protobuf_AssignDesc_Messages_2fbasics_2eproto();
  friend void protobuf_ShutdownFile_Messages_2fbasics_2eproto();

  void InitAsDefaultInstance();
  static SetTimeScale* default_instance_;
};
// -------------------------------------------------------------------

class SystemRequest : public ::google::protobuf::Message {
 public:
  SystemRequest();
  virtual ~SystemRequest();

  SystemRequest(const SystemRequest& from);

  inline SystemRequest& operator=(const SystemRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SystemRequest& default_instance();

  void Swap(SystemRequest* other);

  // implements Message ----------------------------------------------

  SystemRequest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SystemRequest& from);
  void MergeFrom(const SystemRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef SystemRequest_RequestType RequestType;
  static const RequestType SHUT_DOWN = SystemRequest_RequestType_SHUT_DOWN;
  static const RequestType SERIALIZED_STATE = SystemRequest_RequestType_SERIALIZED_STATE;
  static inline bool RequestType_IsValid(int value) {
    return SystemRequest_RequestType_IsValid(value);
  }
  static const RequestType RequestType_MIN =
    SystemRequest_RequestType_RequestType_MIN;
  static const RequestType RequestType_MAX =
    SystemRequest_RequestType_RequestType_MAX;
  static const int RequestType_ARRAYSIZE =
    SystemRequest_RequestType_RequestType_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  RequestType_descriptor() {
    return SystemRequest_RequestType_descriptor();
  }
  static inline const ::std::string& RequestType_Name(RequestType value) {
    return SystemRequest_RequestType_Name(value);
  }
  static inline bool RequestType_Parse(const ::std::string& name,
      RequestType* value) {
    return SystemRequest_RequestType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // required .BuiltIn.SystemRequest.RequestType request = 1;
  inline bool has_request() const;
  inline void clear_request();
  static const int kRequestFieldNumber = 1;
  inline ::BuiltIn::SystemRequest_RequestType request() const;
  inline void set_request(::BuiltIn::SystemRequest_RequestType value);

  // @@protoc_insertion_point(class_scope:BuiltIn.SystemRequest)
 private:
  inline void set_has_request();
  inline void clear_has_request();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  int request_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_Messages_2fbasics_2eproto();
  friend void protobuf_AssignDesc_Messages_2fbasics_2eproto();
  friend void protobuf_ShutdownFile_Messages_2fbasics_2eproto();

  void InitAsDefaultInstance();
  static SystemRequest* default_instance_;
};
// -------------------------------------------------------------------

class SystemResponse : public ::google::protobuf::Message {
 public:
  SystemResponse();
  virtual ~SystemResponse();

  SystemResponse(const SystemResponse& from);

  inline SystemResponse& operator=(const SystemResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SystemResponse& default_instance();

  void Swap(SystemResponse* other);

  // implements Message ----------------------------------------------

  SystemResponse* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SystemResponse& from);
  void MergeFrom(const SystemResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef SystemResponse_ResponseType ResponseType;
  static const ResponseType SHUT_DOWN_RESPONSE = SystemResponse_ResponseType_SHUT_DOWN_RESPONSE;
  static const ResponseType SERIALIZED_STATE_RESPONSE = SystemResponse_ResponseType_SERIALIZED_STATE_RESPONSE;
  static const ResponseType LOG_LEVEL_CHANGED = SystemResponse_ResponseType_LOG_LEVEL_CHANGED;
  static const ResponseType INVALID_REQUEST = SystemResponse_ResponseType_INVALID_REQUEST;
  static inline bool ResponseType_IsValid(int value) {
    return SystemResponse_ResponseType_IsValid(value);
  }
  static const ResponseType ResponseType_MIN =
    SystemResponse_ResponseType_ResponseType_MIN;
  static const ResponseType ResponseType_MAX =
    SystemResponse_ResponseType_ResponseType_MAX;
  static const int ResponseType_ARRAYSIZE =
    SystemResponse_ResponseType_ResponseType_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  ResponseType_descriptor() {
    return SystemResponse_ResponseType_descriptor();
  }
  static inline const ::std::string& ResponseType_Name(ResponseType value) {
    return SystemResponse_ResponseType_Name(value);
  }
  static inline bool ResponseType_Parse(const ::std::string& name,
      ResponseType* value) {
    return SystemResponse_ResponseType_Parse(name, value);
  }

  typedef SystemResponse_ShutdownStatus ShutdownStatus;
  static const ShutdownStatus CLEAN_SHUTDOWN = SystemResponse_ShutdownStatus_CLEAN_SHUTDOWN;
  static const ShutdownStatus UNCLEAN_SHUTDOWN = SystemResponse_ShutdownStatus_UNCLEAN_SHUTDOWN;
  static inline bool ShutdownStatus_IsValid(int value) {
    return SystemResponse_ShutdownStatus_IsValid(value);
  }
  static const ShutdownStatus ShutdownStatus_MIN =
    SystemResponse_ShutdownStatus_ShutdownStatus_MIN;
  static const ShutdownStatus ShutdownStatus_MAX =
    SystemResponse_ShutdownStatus_ShutdownStatus_MAX;
  static const int ShutdownStatus_ARRAYSIZE =
    SystemResponse_ShutdownStatus_ShutdownStatus_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  ShutdownStatus_descriptor() {
    return SystemResponse_ShutdownStatus_descriptor();
  }
  static inline const ::std::string& ShutdownStatus_Name(ShutdownStatus value) {
    return SystemResponse_ShutdownStatus_Name(value);
  }
  static inline bool ShutdownStatus_Parse(const ::std::string& name,
      ShutdownStatus* value) {
    return SystemResponse_ShutdownStatus_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // required .BuiltIn.SystemResponse.ResponseType response = 1;
  inline bool has_response() const;
  inline void clear_response();
  static const int kResponseFieldNumber = 1;
  inline ::BuiltIn::SystemResponse_ResponseType response() const;
  inline void set_response(::BuiltIn::SystemResponse_ResponseType value);

  // optional string state = 2;
  inline bool has_state() const;
  inline void clear_state();
  static const int kStateFieldNumber = 2;
  inline const ::std::string& state() const;
  inline void set_state(const ::std::string& value);
  inline void set_state(const char* value);
  inline void set_state(const char* value, size_t size);
  inline ::std::string* mutable_state();
  inline ::std::string* release_state();
  inline void set_allocated_state(::std::string* state);

  // optional .BuiltIn.SystemResponse.ShutdownStatus shutdownStatus = 3;
  inline bool has_shutdownstatus() const;
  inline void clear_shutdownstatus();
  static const int kShutdownStatusFieldNumber = 3;
  inline ::BuiltIn::SystemResponse_ShutdownStatus shutdownstatus() const;
  inline void set_shutdownstatus(::BuiltIn::SystemResponse_ShutdownStatus value);

  // @@protoc_insertion_point(class_scope:BuiltIn.SystemResponse)
 private:
  inline void set_has_response();
  inline void clear_has_response();
  inline void set_has_state();
  inline void clear_has_state();
  inline void set_has_shutdownstatus();
  inline void clear_has_shutdownstatus();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* state_;
  int response_;
  int shutdownstatus_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_Messages_2fbasics_2eproto();
  friend void protobuf_AssignDesc_Messages_2fbasics_2eproto();
  friend void protobuf_ShutdownFile_Messages_2fbasics_2eproto();

  void InitAsDefaultInstance();
  static SystemResponse* default_instance_;
};
// -------------------------------------------------------------------

class ChangeLogLevel : public ::google::protobuf::Message {
 public:
  ChangeLogLevel();
  virtual ~ChangeLogLevel();

  ChangeLogLevel(const ChangeLogLevel& from);

  inline ChangeLogLevel& operator=(const ChangeLogLevel& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ChangeLogLevel& default_instance();

  void Swap(ChangeLogLevel* other);

  // implements Message ----------------------------------------------

  ChangeLogLevel* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ChangeLogLevel& from);
  void MergeFrom(const ChangeLogLevel& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 logLevel = 1;
  inline bool has_loglevel() const;
  inline void clear_loglevel();
  static const int kLogLevelFieldNumber = 1;
  inline ::google::protobuf::uint32 loglevel() const;
  inline void set_loglevel(::google::protobuf::uint32 value);

  // repeated string includeSystems = 2;
  inline int includesystems_size() const;
  inline void clear_includesystems();
  static const int kIncludeSystemsFieldNumber = 2;
  inline const ::std::string& includesystems(int index) const;
  inline ::std::string* mutable_includesystems(int index);
  inline void set_includesystems(int index, const ::std::string& value);
  inline void set_includesystems(int index, const char* value);
  inline void set_includesystems(int index, const char* value, size_t size);
  inline ::std::string* add_includesystems();
  inline void add_includesystems(const ::std::string& value);
  inline void add_includesystems(const char* value);
  inline void add_includesystems(const char* value, size_t size);
  inline const ::google::protobuf::RepeatedPtrField< ::std::string>& includesystems() const;
  inline ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_includesystems();

  // repeated string excludeSystems = 3;
  inline int excludesystems_size() const;
  inline void clear_excludesystems();
  static const int kExcludeSystemsFieldNumber = 3;
  inline const ::std::string& excludesystems(int index) const;
  inline ::std::string* mutable_excludesystems(int index);
  inline void set_excludesystems(int index, const ::std::string& value);
  inline void set_excludesystems(int index, const char* value);
  inline void set_excludesystems(int index, const char* value, size_t size);
  inline ::std::string* add_excludesystems();
  inline void add_excludesystems(const ::std::string& value);
  inline void add_excludesystems(const char* value);
  inline void add_excludesystems(const char* value, size_t size);
  inline const ::google::protobuf::RepeatedPtrField< ::std::string>& excludesystems() const;
  inline ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_excludesystems();

  // @@protoc_insertion_point(class_scope:BuiltIn.ChangeLogLevel)
 private:
  inline void set_has_loglevel();
  inline void clear_has_loglevel();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::std::string> includesystems_;
  ::google::protobuf::RepeatedPtrField< ::std::string> excludesystems_;
  ::google::protobuf::uint32 loglevel_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_Messages_2fbasics_2eproto();
  friend void protobuf_AssignDesc_Messages_2fbasics_2eproto();
  friend void protobuf_ShutdownFile_Messages_2fbasics_2eproto();

  void InitAsDefaultInstance();
  static ChangeLogLevel* default_instance_;
};
// -------------------------------------------------------------------

class EmptyMessage : public ::google::protobuf::Message {
 public:
  EmptyMessage();
  virtual ~EmptyMessage();

  EmptyMessage(const EmptyMessage& from);

  inline EmptyMessage& operator=(const EmptyMessage& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const EmptyMessage& default_instance();

  void Swap(EmptyMessage* other);

  // implements Message ----------------------------------------------

  EmptyMessage* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const EmptyMessage& from);
  void MergeFrom(const EmptyMessage& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:BuiltIn.EmptyMessage)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;


  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[1];

  friend void  protobuf_AddDesc_Messages_2fbasics_2eproto();
  friend void protobuf_AssignDesc_Messages_2fbasics_2eproto();
  friend void protobuf_ShutdownFile_Messages_2fbasics_2eproto();

  void InitAsDefaultInstance();
  static EmptyMessage* default_instance_;
};
// ===================================================================


// ===================================================================

// SetTimeScale

// required float timeScale = 1;
inline bool SetTimeScale::has_timescale() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SetTimeScale::set_has_timescale() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SetTimeScale::clear_has_timescale() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SetTimeScale::clear_timescale() {
  timescale_ = 0;
  clear_has_timescale();
}
inline float SetTimeScale::timescale() const {
  return timescale_;
}
inline void SetTimeScale::set_timescale(float value) {
  set_has_timescale();
  timescale_ = value;
}

// -------------------------------------------------------------------

// SystemRequest

// required .BuiltIn.SystemRequest.RequestType request = 1;
inline bool SystemRequest::has_request() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SystemRequest::set_has_request() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SystemRequest::clear_has_request() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SystemRequest::clear_request() {
  request_ = 0;
  clear_has_request();
}
inline ::BuiltIn::SystemRequest_RequestType SystemRequest::request() const {
  return static_cast< ::BuiltIn::SystemRequest_RequestType >(request_);
}
inline void SystemRequest::set_request(::BuiltIn::SystemRequest_RequestType value) {
  assert(::BuiltIn::SystemRequest_RequestType_IsValid(value));
  set_has_request();
  request_ = value;
}

// -------------------------------------------------------------------

// SystemResponse

// required .BuiltIn.SystemResponse.ResponseType response = 1;
inline bool SystemResponse::has_response() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SystemResponse::set_has_response() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SystemResponse::clear_has_response() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SystemResponse::clear_response() {
  response_ = 0;
  clear_has_response();
}
inline ::BuiltIn::SystemResponse_ResponseType SystemResponse::response() const {
  return static_cast< ::BuiltIn::SystemResponse_ResponseType >(response_);
}
inline void SystemResponse::set_response(::BuiltIn::SystemResponse_ResponseType value) {
  assert(::BuiltIn::SystemResponse_ResponseType_IsValid(value));
  set_has_response();
  response_ = value;
}

// optional string state = 2;
inline bool SystemResponse::has_state() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void SystemResponse::set_has_state() {
  _has_bits_[0] |= 0x00000002u;
}
inline void SystemResponse::clear_has_state() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void SystemResponse::clear_state() {
  if (state_ != &::google::protobuf::internal::kEmptyString) {
    state_->clear();
  }
  clear_has_state();
}
inline const ::std::string& SystemResponse::state() const {
  return *state_;
}
inline void SystemResponse::set_state(const ::std::string& value) {
  set_has_state();
  if (state_ == &::google::protobuf::internal::kEmptyString) {
    state_ = new ::std::string;
  }
  state_->assign(value);
}
inline void SystemResponse::set_state(const char* value) {
  set_has_state();
  if (state_ == &::google::protobuf::internal::kEmptyString) {
    state_ = new ::std::string;
  }
  state_->assign(value);
}
inline void SystemResponse::set_state(const char* value, size_t size) {
  set_has_state();
  if (state_ == &::google::protobuf::internal::kEmptyString) {
    state_ = new ::std::string;
  }
  state_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* SystemResponse::mutable_state() {
  set_has_state();
  if (state_ == &::google::protobuf::internal::kEmptyString) {
    state_ = new ::std::string;
  }
  return state_;
}
inline ::std::string* SystemResponse::release_state() {
  clear_has_state();
  if (state_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = state_;
    state_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void SystemResponse::set_allocated_state(::std::string* state) {
  if (state_ != &::google::protobuf::internal::kEmptyString) {
    delete state_;
  }
  if (state) {
    set_has_state();
    state_ = state;
  } else {
    clear_has_state();
    state_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional .BuiltIn.SystemResponse.ShutdownStatus shutdownStatus = 3;
inline bool SystemResponse::has_shutdownstatus() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void SystemResponse::set_has_shutdownstatus() {
  _has_bits_[0] |= 0x00000004u;
}
inline void SystemResponse::clear_has_shutdownstatus() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void SystemResponse::clear_shutdownstatus() {
  shutdownstatus_ = 0;
  clear_has_shutdownstatus();
}
inline ::BuiltIn::SystemResponse_ShutdownStatus SystemResponse::shutdownstatus() const {
  return static_cast< ::BuiltIn::SystemResponse_ShutdownStatus >(shutdownstatus_);
}
inline void SystemResponse::set_shutdownstatus(::BuiltIn::SystemResponse_ShutdownStatus value) {
  assert(::BuiltIn::SystemResponse_ShutdownStatus_IsValid(value));
  set_has_shutdownstatus();
  shutdownstatus_ = value;
}

// -------------------------------------------------------------------

// ChangeLogLevel

// optional uint32 logLevel = 1;
inline bool ChangeLogLevel::has_loglevel() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ChangeLogLevel::set_has_loglevel() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ChangeLogLevel::clear_has_loglevel() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ChangeLogLevel::clear_loglevel() {
  loglevel_ = 0u;
  clear_has_loglevel();
}
inline ::google::protobuf::uint32 ChangeLogLevel::loglevel() const {
  return loglevel_;
}
inline void ChangeLogLevel::set_loglevel(::google::protobuf::uint32 value) {
  set_has_loglevel();
  loglevel_ = value;
}

// repeated string includeSystems = 2;
inline int ChangeLogLevel::includesystems_size() const {
  return includesystems_.size();
}
inline void ChangeLogLevel::clear_includesystems() {
  includesystems_.Clear();
}
inline const ::std::string& ChangeLogLevel::includesystems(int index) const {
  return includesystems_.Get(index);
}
inline ::std::string* ChangeLogLevel::mutable_includesystems(int index) {
  return includesystems_.Mutable(index);
}
inline void ChangeLogLevel::set_includesystems(int index, const ::std::string& value) {
  includesystems_.Mutable(index)->assign(value);
}
inline void ChangeLogLevel::set_includesystems(int index, const char* value) {
  includesystems_.Mutable(index)->assign(value);
}
inline void ChangeLogLevel::set_includesystems(int index, const char* value, size_t size) {
  includesystems_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
}
inline ::std::string* ChangeLogLevel::add_includesystems() {
  return includesystems_.Add();
}
inline void ChangeLogLevel::add_includesystems(const ::std::string& value) {
  includesystems_.Add()->assign(value);
}
inline void ChangeLogLevel::add_includesystems(const char* value) {
  includesystems_.Add()->assign(value);
}
inline void ChangeLogLevel::add_includesystems(const char* value, size_t size) {
  includesystems_.Add()->assign(reinterpret_cast<const char*>(value), size);
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
ChangeLogLevel::includesystems() const {
  return includesystems_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
ChangeLogLevel::mutable_includesystems() {
  return &includesystems_;
}

// repeated string excludeSystems = 3;
inline int ChangeLogLevel::excludesystems_size() const {
  return excludesystems_.size();
}
inline void ChangeLogLevel::clear_excludesystems() {
  excludesystems_.Clear();
}
inline const ::std::string& ChangeLogLevel::excludesystems(int index) const {
  return excludesystems_.Get(index);
}
inline ::std::string* ChangeLogLevel::mutable_excludesystems(int index) {
  return excludesystems_.Mutable(index);
}
inline void ChangeLogLevel::set_excludesystems(int index, const ::std::string& value) {
  excludesystems_.Mutable(index)->assign(value);
}
inline void ChangeLogLevel::set_excludesystems(int index, const char* value) {
  excludesystems_.Mutable(index)->assign(value);
}
inline void ChangeLogLevel::set_excludesystems(int index, const char* value, size_t size) {
  excludesystems_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
}
inline ::std::string* ChangeLogLevel::add_excludesystems() {
  return excludesystems_.Add();
}
inline void ChangeLogLevel::add_excludesystems(const ::std::string& value) {
  excludesystems_.Add()->assign(value);
}
inline void ChangeLogLevel::add_excludesystems(const char* value) {
  excludesystems_.Add()->assign(value);
}
inline void ChangeLogLevel::add_excludesystems(const char* value, size_t size) {
  excludesystems_.Add()->assign(reinterpret_cast<const char*>(value), size);
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
ChangeLogLevel::excludesystems() const {
  return excludesystems_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
ChangeLogLevel::mutable_excludesystems() {
  return &excludesystems_;
}

// -------------------------------------------------------------------

// EmptyMessage


// @@protoc_insertion_point(namespace_scope)

}  // namespace BuiltIn

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::BuiltIn::SystemRequest_RequestType>() {
  return ::BuiltIn::SystemRequest_RequestType_descriptor();
}
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::BuiltIn::SystemResponse_ResponseType>() {
  return ::BuiltIn::SystemResponse_ResponseType_descriptor();
}
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::BuiltIn::SystemResponse_ShutdownStatus>() {
  return ::BuiltIn::SystemResponse_ShutdownStatus_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_Messages_2fbasics_2eproto__INCLUDED
